name: payu
channels:
  - accessnri
  - coecms
  - conda-forge
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - annotated-types==0.6.0
  - appdirs==1.4.4
  - attr==2.5.1
  - blosc==1.21.5
  - brotli-python==1.1.0
  - bzip2==1.0.8
  - c-ares==1.28.1
  - ca-certificates==2024.2.2
  - cachecontrol==0.14.0
  - cachecontrol-with-filecache==0.14.0
  - cachy==0.3.0
  - certifi==2024.2.2
  - cffi==1.16.0
  - cftime==1.6.3
  - charset-normalizer==3.3.2
  - click==8.1.7
  - click-default-group==1.2.4
  - clikit==0.6.2
  - colorama==0.4.6
  - conda-lock==2.5.6
  - conda-pack==0.7.1
  - crashtest==0.4.1
  - cryptography==42.0.5
  - curl==8.7.1
  - dbus==1.13.6
  - distlib==0.3.8
  - ensureconda==1.4.4
  - esmf==8.6.0
  - exceptiongroup==1.2.0
  - expat==2.6.2
  - f90nml==1.4.3
  - filelock==3.13.4
  - gettext==0.22.5
  - gettext-tools==0.22.5
  - gh==2.47.0
  - git==2.44.0
  - gitdb==4.0.11
  - gitpython==3.1.43
  - gsl==2.7
  - hdf4==4.2.15
  - hdf5==1.14.3
  - html5lib==1.1
  - icu==73.2
  - idna==3.6
  - importlib-metadata==7.1.0
  - importlib_metadata==7.1.0
  - importlib_resources==6.4.0
  - iniconfig==2.0.0
  - jaraco.classes==3.4.0
  - jaraco.context==4.3.0
  - jaraco.functools==4.0.0
  - jeepney==0.8.0
  - jinja2==3.1.3
  - keyring==25.1.0
  - keyutils==1.6.1
  - krb5==1.21.2
  - ld_impl_linux-64==2.40
  - libaec==1.1.3
  - libasprintf==0.22.5
  - libasprintf-devel==0.22.5
  - libblas==3.9.0
  - libcap==2.69
  - libcblas==3.9.0
  - libcbor==0.10.2
  - libcurl==8.7.1
  - libedit==3.1.20191231
  - libev==4.33
  - libexpat==2.6.2
  - libffi==3.4.2
  - libfido2==1.14.0
  - libgcc-ng==13.2.0
  - libgettextpo==0.22.5
  - libgettextpo-devel==0.22.5
  - libgfortran-ng==13.2.0
  - libgfortran5==13.2.0
  - libglib==2.80.0
  - libgomp==13.2.0
  - libiconv==1.17
  - libjpeg-turbo==3.0.0
  - liblapack==3.9.0
  - libnetcdf==4.9.2
  - libnghttp2==1.58.0
  - libnsl==2.0.1
  - libopenblas==0.3.27
  - libpnetcdf==1.12.3
  - libsqlite==3.45.2
  - libssh2==1.11.0
  - libstdcxx-ng==13.2.0
  - libudev1==255
  - libudunits2==2.2.28
  - libuuid==2.38.1
  - libxcrypt==4.4.36
  - libxml2==2.12.6
  - libzip==1.10.1
  - libzlib==1.2.13
  - lz4-c==1.9.4
  - markupsafe==2.1.5
  - more-itertools==10.2.0
  - mpi==1.0
  - mpich==4.2.0
  - msgpack-python==1.0.7
  - nchash==0.1.5
  - nco==5.2.3
  - ncurses==6.4.20240210
  - netcdf-fortran==4.6.1
  - netcdf4==1.6.5
  - numpy==1.26.4
  - openssh==9.6p1
  - openssl==3.2.1
  - packaging==24.0
  - parallelio==2.6.2
  - pastel==0.2.1
  - accessnri::payu==1.1.3
  - pcre2==10.43
  - perl==5.32.1
  - pip==24.0
  - pkginfo==1.10.0
  - platformdirs==4.2.0
  - pluggy==1.4.0
  - pycparser==2.22
  - pydantic==2.6.4
  - pydantic-core==2.16.3
  - pylev==1.4.0
  - pysocks==1.7.1
  - pytest==8.1.1
  - python==3.9.19
  - python-dateutil==2.9.0
  - python_abi==3.9
  - pyyaml==6.0.1
  - readline==8.2
  - requests==2.31.0
  - ruamel.yaml==0.18.6
  - ruamel.yaml.clib==0.2.8
  - secretstorage==3.3.3
  - setuptools==69.2.0
  - six==1.16.0
  - smmap==5.0.0
  - snappy==1.2.0
  - tempest-remap==2.2.0
  - tenacity==8.2.3
  - tk==8.6.13
  - tomli==2.0.1
  - tomlkit==0.12.4
  - toolz==0.12.1
  - typing-extensions==4.11.0
  - typing_extensions==4.11.0
  - tzdata==2024a
  - urllib3==1.26.18
  - virtualenv==20.25.1
  - webencodings==0.5.1
  - wheel==0.43.0
  - xz==5.2.6
  - yamanifest==0.3.8
  - yaml==0.2.5
  - zipp==3.17.0
  - zlib==1.2.13
  - zstd==1.5.5