name: payu
channels:
  - accessnri
  - coecms
  - conda-forge
dependencies:
  - python==3.10
  # Install changes on payu fork branch
  - pip:
    - git+https://github.com/ACCESS-NRI/payu.git@546-telemetry
  - f90nml
  - gh
  - git
  - nco
  - pytest
  - openssh>=8.3
  - xarray
  - mule
  - um2nc
  - accessnri::yamanifest