name: payu
channels:
  - accessnri
  - coecms
  - conda-forge
dependencies:
  - python==3.10
  # Install changes on payu fork branch
  - pip:
    - git+https://github.com/ACCESS-NRI/payu.git@17-support-container-launcher-script-env
  - f90nml
  - nco
  - pytest
  - accessnri::yamanifest