name: payu-dev
channels:
  - accessnri
  - coecms
  - conda-forge
dependencies:
  - python==3.10
  # Install latest changes from payu
  - pip:
    - git+https://github.com/payu-org/payu.git@master
  - f90nml
  - gh
  - git
  - nco
  - pytest
  - openssh>=8.3
  - xarray
  - mule
  - um2nc
  - accessnri::yamanifest