name: Build, test and deploy conda env
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to update"
        required: true
        type: string
      deploy:
        description: "Run deploy"
        type: boolean
        required: true
      build_and_test:
        description: "Run build and test PBS jobs"
        type: boolean
        required: true
      
jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    environment: Gadi
    steps:
      - name: Check Gadi Github Environment configuration
        run: |
          vars_unset=false
          if [ -z "${{ vars.ADMIN_DIR }}" ]; then
            echo "::error::vars.ADMIN_DIR is unset. ADMIN_DIR is the base directory which will contain the staging and logs sub-directories"
            vars_unset=true
          fi
          if [ -z "${{ vars.CONDA_BASE }}" ]; then
            echo "::error::vars.CONDA_BASE is unset. CONDA_BASE is the base deployment directory which will contain apps and module sub-directories"
            vars_unset=true
          fi
          if [ -z "${{ vars.PRERELEASE_ADMIN_DIR }}" ]; then
            echo "::error::vars.PRERELEASE_ADMIN_DIR is unset. PRERELEASE_ADMIN_DIR is the prerelease base directory which will contain the staging and logs sub-directories"
            vars_unset=true
          fi
          if [ -z "${{ vars.PRERELEASE_CONDA_BASE }}" ]; then
            echo "::error::vars.PRERELEASE_CONDA_BASE is unset. PRERELEASE_CONDA_BASE is the prerelease base deployment directory which will contain apps and module sub-directories"
            vars_unset=true
          fi
          if [ -z "${{ vars.PROJECT }}" ]; then
            echo "::error::vars.PROJECT is unset. PROJECT is the project code passed to build+test qsub calls"
            vars_unset=true
          fi
          if [ -z "${{ vars.STORAGE }}" ]; then
            echo "::error::vars.STORAGE is unset. STORAGE is the storage flags passed to build+test qsub calls"
            vars_unset=true
          fi
          if [ -z "${{ vars.APPS_USERS_GROUP }}" ]; then
            echo "::error::vars.APPS_USERS_GROUP is unset. APPS_USERS_GROUP is used for setting file permissions"
            vars_unset=true
          fi
          if [ -z "${{ vars.APPS_OWNER }}" ]; then
            echo "::error::APPS_OWNER is unset. APPS_OWNER is used for setting file permissions"
            vars_unset=true
          fi
          if [ -z "${{ secrets.REPO_PATH }}" ]; then
            echo "::error::secrets.REPO_PATH is unset. REPO_PATH is the path where this repository is synced to"
            vars_unset=true
          fi
          if [ -z "${{ vars.PRERELEASE_ENVIRONMENTS }}" ]; then
            echo "::error::vars.PRERELEASE_ENVIRONMENTS is unset. PRERELEASE_ENVIRONMENTS is the list of environments to deploy to prerelease directories"
            vars_unset=true
          fi

          if [ "$vars_unset" == "true" ]; then
            echo "::error::Required vars in Gadi Github Environment are unset."
            exit 1
          fi

      - name: Set release/prerelease directories
        run: |
          # Check if environment is in list of prerelease environments
          if [[ '${{ vars.PRERELEASE_ENVIRONMENTS }}' =~ '"${{ matrix.environment }}"' ]]; then
            echo "Using prerelease deployment directories"
            echo "CONDA_BASE=${{ vars.PRERELEASE_CONDA_BASE }}" >> $GITHUB_ENV
            echo "ADMIN_DIR=${{ vars.PRERELEASE_ADMIN_DIR }}" >> $GITHUB_ENV
          else
            echo "Using release deployment directories"
            echo "CONDA_BASE=${{ vars.CONDA_BASE }}" >> $GITHUB_ENV
            echo "ADMIN_DIR=${{ vars.ADMIN_DIR }}" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download base container
        if: inputs.build_and_test
        uses: actions/download-artifact@v4
        with:
            name: base-container
            path: container

      - name: Setup SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Create parent repository directories
        if: inputs.build_and_test
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          mkdir -p ${{ secrets.REPO_PATH }}
          EOT

      - name: Sync repository to Gadi
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            -avz --delete --exclude=/.git/ --exclude=/.github/ \
            ./ \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ secrets.REPO_PATH }}

      - name: Create Admin dirs on Gadi
        if: inputs.build_and_test
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          set -e
          export ADMIN_DIR="${{ env.ADMIN_DIR }}"
          export CONDA_BASE="${{ env.CONDA_BASE }}"
          export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
          export APPS_OWNER="${{ vars.APPS_OWNER }}"
          export REPO_PATH="${{ secrets.REPO_PATH }}"

          source "${REPO_PATH}"/scripts/install_config.sh
          source "${REPO_PATH}"/scripts/functions.sh
          mkdir -p "${ADMIN_DIR}" "${JOB_LOG_DIR}" "${BUILD_STAGE_DIR}"
          set_admin_perms "${ADMIN_DIR}" "${JOB_LOG_DIR}" "${BUILD_STAGE_DIR}"
          EOT

      - name: Build conda environment
        if: inputs.build_and_test
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          set -e
          export SCRIPT_DIR="${{ secrets.REPO_PATH }}/scripts"
          export CONDA_ENVIRONMENT="${{ matrix.environment }}"
          export ADMIN_DIR="${{ env.ADMIN_DIR }}"
          export CONDA_BASE="${{ env.CONDA_BASE }}"
          export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
          export APPS_OWNER="${{ vars.APPS_OWNER }}"
          PROJECT=${{ vars.PROJECT }}
          STORAGE=${{ vars.STORAGE }}

          source "${SCRIPT_DIR}"/install_config.sh
          cd "${JOB_LOG_DIR}"

          qsub -N build_"${CONDA_ENVIRONMENT}" -lncpus=1,mem=20GB,walltime=2:00:00,jobfs=50GB,storage="${STORAGE}" \
            -v SCRIPT_DIR,CONDA_ENVIRONMENT,ADMIN_DIR,CONDA_BASE,APPS_USERS_GROUP,APPS_OWNER \
            -P "${PROJECT}" -q copyq -Wblock=true -Wumask=037 \
            "${SCRIPT_DIR}"/build.sh

          EOT

      - name: Test conda environment
        if: inputs.build_and_test
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          set -e
          export SCRIPT_DIR="${{secrets.REPO_PATH}}/scripts"
          export CONDA_ENVIRONMENT="${{ matrix.environment }}"
          export ADMIN_DIR="${{ env.ADMIN_DIR }}"
          export CONDA_BASE="${{ env.CONDA_BASE }}"
          export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
          export APPS_OWNER="${{ vars.APPS_OWNER }}"
          PROJECT=${{ vars.PROJECT }}
          STORAGE=${{ vars.STORAGE }}

          source "${SCRIPT_DIR}"/install_config.sh
          cd "${JOB_LOG_DIR}"

          qsub -N test_"${CONDA_ENVIRONMENT}" -lncpus=4,mem=20GB,walltime=0:20:00,jobfs=50GB,storage="${STORAGE}" \
            -v SCRIPT_DIR,CONDA_ENVIRONMENT,ADMIN_DIR,CONDA_BASE,APPS_USERS_GROUP,APPS_OWNER \
            -P "${PROJECT}" -Wblock=true -Wumask=037 \
            "${SCRIPT_DIR}"/test.sh

          EOT
  
      - name: Deploy conda environment
        if: inputs.deploy
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          set -e
          export SCRIPT_DIR="${{ secrets.REPO_PATH }}/scripts"
          export CONDA_ENVIRONMENT="${{ matrix.environment }}"
          export ADMIN_DIR="${{ env.ADMIN_DIR }}"
          export CONDA_BASE="${{ env.CONDA_BASE }}"
          export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
          export APPS_OWNER="${{ vars.APPS_OWNER }}"

          source "${SCRIPT_DIR}"/install_config.sh

          "${SCRIPT_DIR}"/deploy.sh

          EOT
