name: Deploy conda env # Generic conda environment deploy
on:
  push:
    branches: main
  # Excludes changes from only environments/payu-dev as this is handled by
  # the deploy_payu_dev.yml workflow
    paths-ignore:
      - 'environments/payu-dev/**'
jobs:
  generate_matrix:
    uses: ./.github/workflows/get_changed_env.yml
    with:
      ignore-environments: '["payu-dev"]'

  deploy:
    needs: [ generate_matrix ]
    if: ${{ needs.generate_matrix.outputs.environments != '[]' }}
    strategy:
      matrix:
        environment: ${{fromJson(needs.generate_matrix.outputs.environments)}}
      max-parallel: 1
      fail-fast: false
    uses: ./.github/workflows/build_test_deploy.yml
    with:
      environment: ${{ matrix.environment }}
      build_and_test: false
      deploy: true
    secrets: inherit
