name: Deploy conda env
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy environment
    runs-on: ubuntu-latest
    environment: Gadi
    steps:
      - name: Setup SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: ${{ secrets.HOST }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy environment
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          set -e
          export SCRIPT_DIR="${{ secrets.REPO_PATH }}/scripts"
          export CONDA_ENVIRONMENT="${{ inputs.environment }}"
          export ADMIN_DIR="${{ vars.ADMIN_DIR }}"
          export CONDA_BASE="${{ vars.CONDA_BASE }}"
          export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
          export APPS_OWNERS_GROUP="${{ vars.APPS_OWNERS_GROUP }}"

          source "${SCRIPT_DIR}"/install_config.sh

          "${SCRIPT_DIR}"/deploy.sh

          EOT