name: Build and test conda env

on: pull_request

jobs:
  generate_matrix:
    uses: ./.github/workflows/get_changed_env.yml

  build_base_image:
    needs: generate_matrix
    if: ${{ needs.generate_matrix.outputs.environments != '[]' }}
    uses: ./.github/workflows/build_base_image.yml

  build-and-test:
    needs: [ generate_matrix, build_base_image ]
    if: ${{ needs.generate_matrix.outputs.environments != '[]' }}
    strategy:
      matrix:
        environment: ${{fromJson(needs.generate_matrix.outputs.environments)}}
      max-parallel: 1
      fail-fast: false
    uses: ./.github/workflows/build_test_deploy.yml
    with:
      environment: ${{ matrix.environment }}
      build_and_test: true
      deploy: false
