name: Deploy conda env
on:
  push:
    branches: main
  # Excludes changes from only environments/payu-dev as this is handled by 
  # the deploy_payu_dev.yml workflow
    paths-ignore:
      - 'environments/payu-dev/**'
jobs:
  generate_matrix:
    uses: ./.github/workflows/get_changed_env.yml
    with:
      ignore-environments: '["payu-dev"]'

  deploy:
    needs: [ generate_matrix ]
    runs-on: ubuntu-latest
    if: ${{ needs.generate_matrix.outputs.environments != '[]' }}
    environment: Gadi
    strategy:
      matrix:
        environment: ${{fromJson(needs.generate_matrix.outputs.environments)}}
      max-parallel: 1
      fail-fast: false
    steps:
      - name: Checkout repository
        ### Latest at time of writing
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Sync repository to Gadi
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            -avz --delete --exclude=/.git/ --exclude=/.github/ \
            ./ \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ secrets.REPO_PATH }}

      - name: Set release/prerelease directories
        run: |
          # Check if environment is in list of prerelease environments
          if [[ '${{ vars.PRERELEASE_ENVIRONMENTS }}' =~ '"${{ matrix.environment }}"' ]]; then
            echo "Using prerelease deployment directories"
            echo "CONDA_BASE=${{ vars.PRERELEASE_CONDA_BASE }}" >> $GITHUB_ENV
            echo "ADMIN_DIR=${{ vars.PRERELEASE_ADMIN_DIR }}" >> $GITHUB_ENV
          else
            echo "Using release deployment directories"
            echo "CONDA_BASE=${{ vars.CONDA_BASE }}" >> $GITHUB_ENV
            echo "ADMIN_DIR=${{ vars.ADMIN_DIR }}" >> $GITHUB_ENV
          fi

      - name: Deploy conda environment
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          set -e
          export SCRIPT_DIR="${{ secrets.REPO_PATH }}/scripts"
          export CONDA_ENVIRONMENT="${{ matrix.environment }}"
          export ADMIN_DIR="${{ env.ADMIN_DIR }}"
          export CONDA_BASE="${{ env.CONDA_BASE }}"
          export APPS_USERS_GROUP="${{ vars.APPS_USERS_GROUP }}"
          export APPS_OWNER="${{ vars.APPS_OWNER }}"

          source "${SCRIPT_DIR}"/install_config.sh

          "${SCRIPT_DIR}"/deploy.sh

          EOT
